### ISSUE TITLE
Unable to decrypt message if 2 subkeys used in public key

### ISSUE THREAD

**Issue by mrmethodist** [jasonhinkle/php-gpg#4]
My PGP public keys use 2 subkeys and when I plug this public key into php-gpg, I'm unable to decrypt it. 

I get two errors;

gpg: public key decryption failed: wrong secret key used 
gpg: decryption failed: secret key not available

But when I revoke one of my subkeys, and only use 1 then I'm able to decrypt the message. I'm guessing you don't have support for multiple subkeys?

**Comment by DanielRuf** [comment]
see #9

**Comment by DanielRuf** [comment]
Was this fixed in https://github.com/jasonhinkle/php-gpg/commit/ec3cfc87c216b1ddcca4b59c8275a60eae076226?

Does this need some more testing? At least this commit works with my keys without any issues.

Or does this need some more testing until it will be merged into master? Before merging with master, #10 may have to be merged into the dev branch.

**Comment by jasonhinkle** [comment]
it appears to be working for me.  I'll close the issue. If anyone still has a problem, please re-open and include a way for us to reproduce.
